services:
  playwright-tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CI: 'true'
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./allure-results:/app/allure-results
      - ./test-results:/app/test-results